export interface INokiaTXNNetworkElement {
  id: number;
  id_class: number;
  alarm_synthesis: string;
  ason_ctr_plane_type: string;
  ct_access_status: string | null;
  comment1: string | null;
  comment2: string | null;
  communication_state: string;
  eth_present: "Boolean_true" | "Boolean_false";
  hierarchy_subnet: string;
  is_multi_nes: boolean | null;
  localization: string;
  latitude: string;
  longitude: string;
  altitude: string;
  mib_alignment_state: string;
  ne_alignment: string;
  ne_sub_type: string;
  key: string;
  loopback_ip: string | null;
  secondary_address: string | null;
  class_name: string;
  otn_conf_downld_st: string;
  parent_id: number;
  parent_label: string;
  position: string;
  sdh_present: "Boolean_true" | "Boolean_false";
  supervision_state: string;
  gui_label: string;
  version: string;
  wdm_present: "Boolean_true" | "Boolean_false";
  conf_downld_st: string;
  nad_string: string;
  product_name: string;
  reachable: "Boolean_true" | "Boolean_false";
  short_product_name: string;
  site_name: string;
  node_type: string;
  eml_ne_type: string;
  comment3: string | null;
  association_present: "Boolean_true" | "Boolean_false";
  ne_sub_release: string;
  associated_ptn_ne_id: number | null;
  comments: string | null;
  actual_release: string;
  audit_status: string;
  new_communication_state: string;
  new_supervision_state: string;
  alignment_state: string;
  creation_date: string;
  modified_date: string;
  created_by: string;
  modified_by: string;
  latest_note: string | null;
  scheduled_for_gri: string;
  system_abnormal_state: "Boolean_true" | "Boolean_false";
  system_mode: string;
}
