enum dropDownsCategory {
  NCE_SEVERITY = "NCE_ALARM_SEVERITY",
  OBS_SEVERITY = "OBS_ALARM_SEVERITY",
  NCE_GPON_SEVERITY = "NCE_GPON_ALARM_SEVERITY",
  NOKIA_TXN_ALARM_SEVERITY = "NOKIA_TXN_ALARM_SEVERITY",
  LDI_SOFTSWITCH_ALARM_SEVERITY = "LDI_SOFTSWITCH_ALARM_SEVERITY",
  ALARM_STATUS = "ALARM_STATUS",
  ALARM_TYPE = "ALARM_TYPE",
  NCE_ALARM_FIELD_NAMES = "NCE_ALARM_FIELD_NAMES",
  OBS_ALARM_FIELD_NAMES = "OBS_ALARM_FIELD_NAMES",
  GPON_ALARM_FIELD_NAMES = "GPON_ALARM_FIELD_NAMES",
  NOKIA_TXN_ALARM_FIELD_NAMES = "NOKIA_TXN_ALARM_FIELD_NAMES",
  LDI_SOFTSWITCH_ALARM_FIELD_NAME = "LDI_SOFTSWITCH_ALARM_FIELD_NAME",
  ALARM_FILTER_ADVANCE_CONDITION_SEARCH_CRITERIA = "ALARM_FILTER_ADVANCE_CONDITION_SEARCH_CRITERIA",
  TROUBLE_TICKET_STATUS = "TROUBLE_TICKET_STATUS",
  TROUBLE_TICKET_MEDIUM = "TROUBLE_TICKET_MEDIUM",
  TICKET_GENERATION_TYPE = "TROUBLE_TICKET_GENERATION_TYPE",
  TROUBLE_TICKET_PRIORITY = "TROUBLE_TICKET_PRIORITY",
}

export { dropDownsCategory };
